#!/bin/bash

# Must change all ram9 to jre4 and Elliott to Gromacs or Gromacs/MBAR

Compound=Ethane

#MolWt=30.0698

Model=TraPPEfs

iEpsref=0

iSigref=0

eps_low=0.85
eps_high=1.2

TOL_eps=0.1

eps_guess=1.0143 #122 K

sigma_guess=0.377 #nm

direct=0 #1-simulate reference, 0-skip simulate reference

for iEpsref in $(seq 0 1)
do

if [ $direct -gt 0 ]

then

#### Start the mdrun simulations for the initial epsilon and sigma values

echo Run ITIC for Epsilon = "$eps_guess" sigma = "$sigma_guess"
sleep 2s

####

cd /home/ram9/"$Compound"/Gromacs/"$Model" || exit 

mkdir e"$iEpsref"s"$iSigref"
cd e"$iEpsref"s"$iSigref" || exit

#Create files with force field parameters

echo "$eps_guess" "$sigma_guess" > eps_Sigma

cp /home/ram9/"$Compound"/Gromacs/Force_switch/ethane_temp.top ethane.top 
cp /home/ram9/"$Compound"/Gromacs/Force_switch/ethane.gro ethane.gro 
sed -i -e s/some_epsilon/"$eps_guess"/ ethane.top
sed -i -e s/some_sigma/"$sigma_guess"/ ethane.top

cp /home/ram9/Elliott/EthaneRunITIC_all EthaneRunITIC_all

sed -i -e s/some_compound_top/"${Compound}"/ EthaneRunITIC_all
sed -i -e s/some_model_top/"${Model}"/ EthaneRunITIC_all
sed -i -e s/some_iSigma_top/"${iSigref}"/ EthaneRunITIC_all
sed -i -e s/some_iEps_top/"${iEpsref}"/ EthaneRunITIC_all

./EthaneRunITIC_all


fi

#Obtain the REFPROP values at the ITIC conditions

#python ~/Elliott/generate_REFPROP_values.py #Antequated code that is no longer necessary but might be useful someday



cd /home/ram9/"$Compound"/Gromacs/"$Model"/e"$iEpsref"s"$iSigref" || exit

echo "Eps (kJ/mol)" > eps_all
echo "Objective" > F_all
echo $TOL_eps > TOL_eps 

echo "$eps_low" > X0_current
echo "$eps_high" > X3_current
echo "$eps_guess" > X1_current

python ~/Elliott/first_step_eps.py

sleep 5s

iteration=0
conv_eps=0

# Iterate to optimize epsilon only

#for iteration in $(seq 0 10) #Start at 2 since we already did 0-1
#do

while [ "$conv_eps" -lt 1 ] #Checks to see if the loop has converged for epsilon

do

cd /home/ram9/"$Compound"/Gromacs/"$Model"/e"$iEpsref"s"$iSigref" || exit 

echo "$iteration" > iEps_iteration

python ~/Elliott/single_iteration_step_eps.py

conv_eps=$(<conv_eps)

eps_it=$(<eps_it_"$iteration")
echo "$eps_it" >> eps_all
sig_it="$sigma_guess" #Sigma is held constant

# Perform the rerun simulations 


echo Reference Epsilon = "$eps_guess" sigma = "$sigma_guess"
echo MBAR rerun Epsilon = "$eps_it" sigma = "$sig_it"
sleep 2s

####

# copy and set force field files

cd /home/ram9/"$Compound"/Gromacs/"$Model"/e"$iEpsref"s"$iSigref" || exit #Must cd back 

echo "$eps_it" "$sig_it" >> eps_Sigma_all

cp /home/ram9/"$Compound"/Gromacs/Force_switch/ethane_temp.top ethane_e"$iteration"s"$iSigref".top
sed -i -e s/some_epsilon/"$eps_it"/ ethane_e"$iteration"s"$iSigref".top 
sed -i -e s/some_sigma/"$sig_it"/ ethane_e"$iteration"s"$iSigref".top

cp /home/ram9/Elliott/EthaneRerunITIC_all EthaneRerunITIC_all

sed -i -e s/some_compound_top/"${Compound}"/ EthaneRerunITIC_all
sed -i -e s/some_model_top/"${Model}"/ EthaneRerunITIC_all
sed -i -e s/some_iSigma_top/"${iSigref}"/ EthaneRerunITIC_all
sed -i -e s/some_iEps_top/"${iteration}"/ EthaneRerunITIC_all
sed -i -e s/some_iRefSig_top/"${iSigref}"/ EthaneRerunITIC_all
sed -i -e s/some_iRefEps_top/"${iEpsref}"/ EthaneRerunITIC_all

./EthaneRerunITIC_all

# Perform MBAR and calculate objective function

python ~/Elliott/objective_from_MBAR.py

cd /home/ram9/"$Compound"/Gromacs/"$Model"/e"$iEpsref"s"$iSigref" || exit #Must cd back to original location

cp F_it_temp F_it_"$iteration"
rm F_it_temp

F_new=$(<F_it_"$iteration")

echo "$F_new" >> F_all

iteration=$((iteration + 1))

done #for while loop

eps_optimal=$(<eps_optimal)
iEpsref=$((iEpsref + 1))

#done #for iteration

#done #for iEpsref of direct simulations

exit 0

#######

