#!/bin/bash

Compound=some_compound
scripts_path=some_scripts_path

#MolWt=30.0698

Model=some_model
iRerun=some_iRerun
iRef=some_iRef

scripts_path=some_scripts_path
input_path=some_input_path
output_path=some_output_path

#========Isochore Settings=====

   Tic0=(137 198.5)		#
   Tic1=(174 234.6)		#	 
   Tic2=(207 262.9)		# 			
   Tic3=(236 285.1)		# 			
   Tic4=(260 301.9)		# 			

#========End Isochore Settings=====

j_start=0
j_end=4


####

# Initialize the folders

for j in $(seq $j_start $j_end)

do

if [ "$j" -eq "0" ]; then Tic="${Tic0[@]}"; fi  
if [ "$j" -eq "1" ]; then Tic="${Tic1[@]}"; fi 
if [ "$j" -eq "2" ]; then Tic="${Tic2[@]}"; fi  
if [ "$j" -eq "3" ]; then Tic="${Tic3[@]}"; fi  
if [ "$j" -eq "4" ]; then Tic="${Tic4[@]}"; fi  

t=-1  #do not put space after equal sign. 
for Temp in ${Tic} 
do
t=$((t+1))

cd "$output_path"/ref"$iRef"/Isochore/rho"$j"/T"$t"/NVT_eq/NVT_prod || exit

cp "$input_path"/md_nocord.mdp md_nocord.mdp 

sed -i -e s/some_temperature/"$Temp"/ md_nocord.mdp #Temperature might not matter in rerun

gmx grompp -f md_nocord.mdp -p ../../../../../ethane_ref"$iRef"rr"$iRerun".top -c nvt_prod.gro -o prod_ref"$iRef"rr"$iRerun" -maxwarn 1

gmx mdrun -table ../../../../../tab_it.xvg -nt 1 -rerun nvt_prod.trr -deffnm prod_ref"$iRef"rr"$iRerun"

echo "1
3
5
7
8
0" | gmx energy -dp -f prod_ref"$iRef"rr"$iRerun".edr -o energy_press_ref"$iRef"rr"$iRerun".xvg

rm -f \#*
rm -f prod_ref*rr*.log
rm -f prod_ref*rr*.tpr
rm -f prod_ref*rr*.edr

done #for t

done #for j

echo "Waiting for Isochore reruns to finish"

sleep 1s

exit 0

#######

