#!/bin/bash

Compound=some_compound_top

#MolWt=30.0698

Model=some_model_top
iRef=some_iRef_top
scripts_path=some_scripts_path_top
input_path=some_input_path_top
output_path=some_output_path_top

cd "$output_path"/ref"$iRef" || exit #Must cd back 

cp "$scripts_path"/EthaneRerunIsochore EthaneRerunIsochore
cp "$scripts_path"/EthaneRerunIsotherm EthaneRerunIsotherm

iRerun=$(<iRerun)

sed -i -e s/some_compound/"${Compound}"/ EthaneRerunIsochore
sed -i -e s/some_model/"${Model}"/ EthaneRerunIsochore
sed -i -e s/some_iRerun/"${iRerun}"/ EthaneRerunIsochore
sed -i -e s/some_iRef/"${iRef}"/ EthaneRerunIsochore
sed -i -e s@some_scripts_path@"$scripts_path"@ EthaneRerunIsochore
sed -i -e s@some_output_path@"$output_path"@ EthaneRerunIsochore

sed -i -e s/some_compound/"${Compound}"/ EthaneRerunIsotherm
sed -i -e s/some_model/"${Model}"/ EthaneRerunIsotherm
sed -i -e s/some_iRerun/"${iRerun}"/ EthaneRerunIsotherm
sed -i -e s/some_iRef/"${iRef}"/ EthaneRerunIsotherm
sed -i -e s@some_scripts_path@"$scripts_path"@ EthaneRerunIsotherm
sed -i -e s@some_output_path@"$output_path"@ EthaneRerunIsotherm

eps_it=$(<eps_it)
eps_guess=$(<eps_guess)
#echo "$eps_it" >> eps_all

sig_it=$(<sig_it) #Sigma is held constant
sig_guess=$(<sig_guess)
#echo "$sig_it" >> sig_all

bond_length=$(<bond_length)

# Perform the rerun simulations 

echo Reference Epsilon = "$eps_guess" sigma = "$sig_guess"
echo MBAR rerun Epsilon = "$eps_it" sigma = "$sig_it"
sleep 2s

####

# copy and set force field files

cd "$output_path"/ref"$iRef" || exit #Must cd back 

echo "$eps_it" "$sig_it" >> eps_Sigma_all

# I can move this inside the EthaneRerunITIC_all

cp "$input_path"/ethane_temp.top ethane_ref"$iRef"rr"$iRerun".top
sed -i -e s/some_epsilon/"$eps_it"/ ethane_ref"$iRef"rr"$iRerun".top 
sed -i -e s/some_sigma/"$sig_it"/ ethane_ref"$iRef"rr"$iRerun".top
sed -i -e s/some_bond/"$bond_length"/ ethane_ref"$iRef"rr"$iRerun".top


./EthaneRerunIsochore
./EthaneRerunIsotherm

exit 0

#######

