#!/bin/bash

Compound=some_compound

Model=some_model

iRerun=some_iRerun
iRef=some_iRef

scripts_path=some_scripts_path
output_path=some_output_path

Temp=(360 360 360 360 360 360 360 360 360)

j_start=0
j_end=8

####

# Production period for isotherm

for j in $(seq $j_start $j_end)

do

cd "$output_path"/ref"$iRef"/Isotherm/rho_"$j"/NVT_eq/NVT_prod || exit

cp "$scripts_path"/md_nocord.mdp md_nocord.mdp 

sed -i -e s/some_temperature/"${Temp[j]}"/ md_nocord.mdp #Temperature might not matter in rerun

gmx grompp -f md_nocord.mdp -p ../../../../ethane_ref"$iRef"rr"$iRerun".top -c nvt_prod.gro -o prod_ref"$iRef"rr"$iRerun" -maxwarn 1

gmx mdrun -nt 1 -rerun nvt_prod.trr -deffnm prod_ref"$iRef"rr"$iRerun"

echo "1
3
5
7
8
0" | gmx energy -dp -f prod_ref"$iRef"rr"$iRerun".edr -o energy_press_ref"$iRef"rr"$iRerun".xvg

rm -f \#*
rm -f prod_ref*rr*.log
rm -f prod_ref*rr*.tpr
rm -f prod_ref*rr*.edr

done

exit 0
