#!/bin/bash

Compound=some_compound_top

#MolWt=30.0698

Model=some_model_top
iRef=some_iRef_top
scripts_path=some_scripts_path_top
input_path=some_input_path_top
output_path=some_output_path_top

cd "$output_path"/ref"$iRef" || exit #Must cd back 

cp "$scripts_path"/EthaneRerunIsochore_tabulated_parallel EthaneRerunIsochore
cp "$scripts_path"/EthaneRerunIsotherm_tabulated_parallel EthaneRerunIsotherm

iRerun=$(<iRerun)

sed -i -e s/some_compound/"${Compound}"/ EthaneRerunIsochore
sed -i -e s/some_model/"${Model}"/ EthaneRerunIsochore
sed -i -e s/some_iRerun/"${iRerun}"/ EthaneRerunIsochore
sed -i -e s/some_iRef/"${iRef}"/ EthaneRerunIsochore
sed -i -e s@some_scripts_path@"$scripts_path"@ EthaneRerunIsochore
sed -i -e s@some_input_path@"$input_path"@ EthaneRerunIsochore
sed -i -e s@some_output_path@"$output_path"@ EthaneRerunIsochore

sed -i -e s/some_compound/"${Compound}"/ EthaneRerunIsotherm
sed -i -e s/some_model/"${Model}"/ EthaneRerunIsotherm
sed -i -e s/some_iRerun/"${iRerun}"/ EthaneRerunIsotherm
sed -i -e s/some_iRef/"${iRef}"/ EthaneRerunIsotherm
sed -i -e s@some_scripts_path@"$scripts_path"@ EthaneRerunIsotherm
sed -i -e s@some_input_path@"$input_path"@ EthaneRerunIsotherm
sed -i -e s@some_output_path@"$output_path"@ EthaneRerunIsotherm

eps_it=$(<eps_it)
eps_guess=$(<eps_guess)

sig_it=$(<sig_it)
sig_guess=$(<sig_guess)

lam_it=$(<lam_it) 
lam_guess=$(<lam_guess)

python "$scripts_path"/create_tab.py --lam "$lam_it" --epsilon "$eps_it" --sigma "$sig_it"

C6_it=$(<C6_it)
Clam_it=$(<Clam_it)

bond_length=$(<bond_length)

# Perform the rerun simulations 

echo Reference Epsilon = "$eps_guess" sigma = "$sig_guess" lambda = "$lam_guess"
echo MBAR rerun Epsilon = "$eps_it" sigma = "$sig_it" lambda = "$lam_it"
sleep 2s

####

# copy and set force field files

cd "$output_path"/ref"$iRef" || exit #Must cd back 

echo "$eps_it" "$sig_it" "$lam_it" >> eps_sig_lam_all

# I can move this inside the EthaneRerunITIC_all

cp "$input_path"/ethane_temp.top ethane_ref"$iRef"rr"$iRerun".top
sed -i -e s/some_C6/"$C6_it"/ ethane_ref"$iRef"rr"$iRerun".top 
sed -i -e s/some_Clam/"$Clam_it"/ ethane_ref"$iRef"rr"$iRerun".top
sed -i -e s/some_bond/"$bond_length"/g ethane_ref"$iRef"rr"$iRerun".top


./EthaneRerunIsochore
./EthaneRerunIsotherm

exit 0

#######

